import styles from "../styles/Home.module.scss";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import About from "../components/About";

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <About />
    </div>
  );
}
